version: "3"
services:
  frontend:
    image: ghcr.io/kitconcept/voltolighttheme-frontend:latest
    restart: always
    hostname: plone-frontend
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      #RAZZLE_API_PATH: https://tommyeriksen.dk/
      #ADDONS: volto-industry-theme
    depends_on:
      - backend
    networks:
      - ix-nginx-proxy-manager_default
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.labels.corebox == true

  backend:
    image: plone/plone-backend:latest
    restart: always
    hostname: plone-backend
    environment:
      SITE: Plone
      ZEO_ADDRESS: db:8100
      PROFILES: plone.volto:default-homepage
      ADDONS: collective.volto.sitesettings

    networks:
      - ix-nginx-proxy-manager_default
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.labels.corebox == true

  db:
    image: plone/plone-zeo:latest
    restart: always
    volumes:
      - plonedata:/data
    networks:
      - ix-nginx-proxy-manager_default
    deploy:
      placement:
        constraints:
          - node.labels.corebox == true

volumes:
  plonedata:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.2,nfsvers=4,rw"
      device: ":/mnt/storage/kubenfs/plone"
      
networks:
  ix-nginx-proxy-manager_default:
    external: true
# from https://6.docs.plone.org/install/containers/examples/nginx-volto-plone-zeo.html
